name:                quine
version:             0.1.0.0
github:              "jar2333/quine"
license:             BSD3
author:              "Jose A. Ramos, Yiming Fang"
maintainer:          "example@example.com"
copyright:           "Jose A. Ramos, Yiming Fang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jar2333/quine#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - array
  - base
  - bytestring
  - hashtables
  - containers
  - mtl
  - logict
  - megaparsec
  - containers
  build-tools:
  - alex
  - happy

executables:
  quine:
    main:                Quine.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quine
    - mtl

  repl:
    main:                Repl.hs
    source-dirs:         app/repl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quine
    - mtl

tests:
  kanren:
    main:                KanrenTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quine
    - HUnit
    
